In [ ]:
import numpy as np
from scipy.linalg import lu, solve

#Для воспроизводительности результатов устанавливаем seed
np.random.seed(42)

In [2]:
import numpy as np
from scipy.linalg import lu, solve

#Для воспроизводительности результатов устанавливаем seed
np.random.seed(42)
#Задание 1
#Создать квадратную матрицу из случайных вещественных чисел из
#(2,4) размера 8 . Найти скалярное произведение 3 строки на 8 столбец.
#Использовать срезы матриц.

matrix_a1 = np.random.uniform(2, 4, size = (8,8))
print(f"Матрица А1 (8x8):\n{matrix_a1}\n")

row_3 = matrix_a1[2,:]
col_8 = matrix_a1[:,7]

scalar_res = np.sum(row_3 * col_8)
print(f"3-я строка матрицы: {row_3}")
print(f"8-ой столбец матрицы: {col_8}")
print(f"Скалярное произведение 3-й строки на 8-й столбец: {scalar_res:.4f}")

Матрица А1 (8x8):
[[2.74908024 3.90142861 3.46398788 3.19731697 2.31203728 2.31198904
  2.11616722 3.73235229]
 [3.20223002 3.41614516 2.04116899 3.9398197  3.66488528 2.42467822
  2.36364993 2.36680902]
 [2.60848449 3.04951286 2.86389004 2.58245828 3.22370579 2.27898772
  2.5842893  2.73272369]
 [2.91213997 3.57035192 2.39934756 3.02846888 3.18482914 2.09290083
  3.2150897  2.34104825]
 [2.13010319 3.89777107 3.93126407 3.6167947  2.60922754 2.19534423
  3.36846605 2.88030499]
 [2.24407647 2.99035382 2.06877704 3.8186408  2.51755996 3.32504457
  2.62342215 3.04013604]
 [3.09342056 2.36970891 3.93916926 3.55026565 3.87899788 3.7896547
  3.19579996 3.84374847]
 [2.176985   2.39196572 2.09045458 2.65066066 2.77735458 2.54269806
  3.65747502 2.71350665]]

3-я строка матрицы: [2.60848449 3.04951286 2.86389004 2.58245828 3.22370579 2.27898772
 2.5842893  2.73272369]
8-ой столбец матрицы: [3.73235229 2.36680902 2.73272369 2.34104825 2.88030499 3.04013604
 3.84374847 2.71350665]
Скалярное про

In [3]:
import numpy as np
from scipy.linalg import lu, solve

#Для воспроизводительности результатов устанавливаем seed
np.random.seed(42)

#Задание 2
#Создать две матрицы из случайных целых чисел из отрезка [-2,6]
#подходящего размера. Найти их произведение тремя способами: 1)
#записав скалярный алгоритм умножения матриц 2) записав векторный
#алгоритм, записав матрицу С 3) проверив с помощью функции np.dot.

m,k,n = 4,5,3

matrix_a2 = np.random.randint(-2, 7, size = (m,k))
matrix_b2 = np.random.randint(-2, 7, size = (k,n))

print(f"Матрица А2 ({m}x{k}):\n{matrix_a2}\n")
print(f"Матрица B2 ({k}x{n}):\n{matrix_b2}\n")

#Скалярный алгоритм
def matrix_multiply_scalar(A,B):
    m,k = A.shape
    k2,n =  B.shape
    C = np.zeros((m,n))
    for i in range(m):
        for j in range(n):
            for t in range(k):
                C[i, j] += A[i,t] * B[t,j]
    return C

def matrix_multiply_vector(A,B):
    m, k = A.shape
    k2, n = B.shape
    C = np.zeros((m,n))

    for i in range(m):
        for j in range(n):
            for t in range(k):
                C[i, j] = np.dot(A[i,:], B[:,j])
    return C

C_scalar = matrix_multiply_scalar(matrix_a2, matrix_b2)
print("Результат скалярного алгоритма:\n", C_scalar)

C_vector = matrix_multiply_vector(matrix_a2, matrix_b2)
print("\nРезультат векторного алгоритма:\n", C_vector)

C_dot = np.dot(matrix_a2, matrix_b2)
print("\nРезультат np.dot:\n", C_dot)

Матрица А2 (4x5):
[[ 4  1  5  2  4]
 [ 0  4  5  2  1]
 [ 5  5  0  3  2]
 [-1  5  3 -1  2]]

Матрица B2 (5x3):
[[-2  3  6]
 [-2  0  4]
 [ 1  6  0]
 [ 2  0  4]
 [ 2  6  4]]

Результат скалярного алгоритма:
 [[  7.  66.  52.]
 [  3.  36.  28.]
 [-10.  27.  70.]
 [ -3.  27.  18.]]

Результат векторного алгоритма:
 [[  7.  66.  52.]
 [  3.  36.  28.]
 [-10.  27.  70.]
 [ -3.  27.  18.]]

Результат np.dot:
 [[  7  66  52]
 [  3  36  28]
 [-10  27  70]
 [ -3  27  18]]


In [4]:
import numpy as np
from scipy.linalg import lu, solve

#Для воспроизводительности результатов устанавливаем seed
np.random.seed(42)

#Задание 3
#Создать произвольную нижнетреугольную матрицу А 5 порядка (не
#унитреугольную), вектор B произвольный. Решить систему AX = B.

matrix_a3 = np.tril(np.random.uniform(1, 5, size = (5,5)))
np.fill_diagonal(matrix_a3, np.random.uniform(2, 5, size = 5))

print(f"Нижнетреугольная матрица A (5x5):\n{matrix_a3}\n")

matrix_b3 = np.random.uniform(1, 10, size = 5)
print(f"Вектор B:\n{matrix_b3}\n")

def solve_lower_triangular(L,b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n):
        sum_val = np.dot(L[i,:i], x[:i])
        x[i] = (b[i] - sum_val) / L[i,i]
    return x

X3 = solve_lower_triangular(matrix_a3, matrix_b3)
print(f"Решение системы X: {X3}\n")

X3_check = np.linalg.solve(matrix_a3, matrix_b3)
print(f"Решение системы X: {X3_check}\n")
print(f"Невязка:{np.linalg.norm(matrix_a3 @ X3_check - matrix_b3)}")
print(f"Совпадение решений: {np.allclose(X3, X3_check)}")

Нижнетреугольная матрица A (5x5):
[[4.35552788 0.         0.         0.         0.        ]
 [1.62397808 2.59902135 0.         0.         0.        ]
 [1.08233798 4.87963941 3.54270332 0.         0.        ]
 [1.73361804 2.21696897 3.09902573 3.77724371 0.        ]
 [3.44741158 1.55797544 2.16857859 2.46544737 2.13935124]]

Вектор B:
[6.46790367 2.53471711 1.58546434 9.53996984 9.6906883 ]

Решение системы X: [ 1.48498732  0.04737562 -0.07140587  1.87486641  0.01401384]

Решение системы X: [ 1.48498732  0.04737562 -0.07140587  1.87486641  0.01401384]

Невязка:1.7763568394002505e-15
Совпадение решений: True


In [8]:
import numpy as np
from scipy.linalg import lu, solve

#Для воспроизводительности результатов устанавливаем seed
np.random.seed(42)

#Задание 4
#Решить систему, используя LU разложение

#Система уравнений:
#14.4x₁ - 5.3x₂ + 14.3x₃ - 12.7x₄ = 14.4
#23.4x₁ - 14.2x₂ - 5.4x₃ + 2.1x₄ = 6.6
#6.3x₁ - 13.2x₂ - 6.5x₃ + 14.3x₄ = 9.4
#5.6x₁ + 8.8x₂ - 6.7x₃ - 23.8x₄ = 7.3

#Матрица коэффициентов A
matrix_a4 = np.array([
    [14.4, -5.3, 14.3, -12.7],
    [23.4, -14.2, -5.4, 2.1],
    [6.3, -13.2, -6.5, 14.3],
    [5.6, 8.8, -6.7, -23.8]
])

#Вектор правых частей B
matrix_b4 = np.array([14.4, 6.6, 9.4, 7.3])
print(f"Матрица А4 (4х4):\n{matrix_a4}\n")
print(f"Вектор B:\n{matrix_b4}\n")

#lu возвращает P, L, U такие, что A = P^T @ L @ U
P, L, U = lu(matrix_a4)
print("Матрица L:\n", L)
print("\nМатрица U:\n", U)
print("Матрица перестановок P:\n", P)

B_permuted = P.T @ matrix_b4

def solve_lower_unit(L, b):
    n = len(b)
    y = np.zeros(n)
    for i in range(n):
        y[i] = b[i] - np.dot(L[i,:i], y[:i])
    return y

def solve_upper(U, y):
    n = len(y)
    x = np.zeros(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.dot(U[i,i+1:], x[i+1:])) / U[i,i]
    return x

#Ly = PB
Y = solve_lower_unit(L, B_permuted)
print(f"\nПромежуточный вектор Y (решение Ly = PB):\n{Y}\n")

#Ux = Y
X4 = solve_upper(U, Y)
print(f"Итоговое решение X (LU-разложение):\n{X4}\n")

X4_check = solve(matrix_a4, matrix_b4)
print(f"Решение системы X (scipy.solve):\n{X4_check}\n")

#Проверка невязки
residual = np.linalg.norm(matrix_a4 @ X4 - matrix_b4)
print(f"\nНевязка ||AX - B||: {residual:.2e}")
print(f"Совпадение с эталонным решением: {np.allclose(X4, X4_check)}")

Матрица А4 (4х4):
[[ 14.4  -5.3  14.3 -12.7]
 [ 23.4 -14.2  -5.4   2.1]
 [  6.3 -13.2  -6.5  14.3]
 [  5.6   8.8  -6.7 -23.8]]

Вектор B:
[14.4  6.6  9.4  7.3]

Матрица L:
 [[ 1.          0.          0.          0.        ]
 [ 0.23931624  1.          0.          0.        ]
 [ 0.61538462  0.28188061  1.          0.        ]
 [ 0.26923077 -0.76870796 -0.48064436  1.        ]]

Матрица U:
 [[ 23.4        -14.2         -5.4          2.1       ]
 [  0.          12.1982906   -5.40769231 -24.3025641 ]
 [  0.           0.          19.1474005   -7.14188621]
 [  0.           0.           0.          -8.37966637]]
Матрица перестановок P:
 [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]]

Промежуточный вектор Y (решение Ly = PB):
[ 6.6         5.72051282  8.72595992 16.21456404]

Итоговое решение X (LU-разложение):
[-1.73206342 -3.50403348 -0.26601589 -1.93498921]

Решение системы X (scipy.solve):
[-1.73206342 -3.50403348 -0.26601589 -1.93498921]


Невязка ||AX - B||: 9.61e-15
Совпаде