In [3]:
import numpy as np
from numpy import linalg as LA
#Задание 1
#Создать вектор-столбец 9x1 из случайных целых чисел. Вычислить норму ||x||_2
#самостоятельно написанной функцией и проверить результат
#с помощью linalg.norm()

#создаем вектор-столбец 9x1 и вычислить норму ||x||_2
np.random.seed(42) #для воспроизводимости
vector = np.random.randint(-10, 11, size = (9, 1))
print(f"\nВектор-столбец (9x1):\n{vector}")

def norm_l2_custom(x):
    return np.sqrt(np.sum(x**2))

norm_custom = norm_l2_custom(vector)
print(f"\nL2-норма (самостоятельно):\n{norm_custom:.6f}")

norm_check = LA.norm(vector, ord = 2)
print(f"\nL2-норма (linalg.norm): {norm_check:.6f}")
print(f"Совпадение: {np.isclose(norm_custom, norm_check)}")


Вектор-столбец (9x1):
[[-4]
 [ 9]
 [ 4]
 [ 0]
 [-3]
 [10]
 [-4]
 [ 8]
 [ 0]]

L2-норма (самостоятельно):
17.378147

L2-норма (linalg.norm): 17.378147
Совпадение: True


In [7]:
import numpy as np
from numpy import linalg as LA
#Задание 2
#Создать матрицу из случайных целых чисел. Найти норму матрицы ||A||_8
#с помощью самостоятельно написанного алгоритма, проверить
#результат с помощью linalg.norm().
np.random.seed(42)
matrix = np.random.randint(-10, 11, size = (5, 5))
print(f"\nМатрица (5x5):\n{matrix}")

def norm_inf_custom(A):
    row_sums = np.sum(np.abs(A), axis = 1)
    return np.max(row_sums)

norm_inf_custom_val = norm_inf_custom(matrix)
print(f"Бесконечная норма (самостоятельно): {norm_inf_custom_val:.6f})")

norm_inf_check = LA.norm(matrix, ord = np.inf)
print(f"Бесконечная норма (linalg.norm): {norm_inf_check:.6f})")
print(f"Совпадение: {np.isclose(norm_inf_custom_val, norm_inf_check)}"
      )



Матрица (5x5):
[[ -4  -2 -10   1  -3]
 [  0   8   6  -3  -8]
 [ -8 -10  -6  -1  -4]
 [ -2  -4  -2  -3   1]
 [ -9 -10   5  -6  -8]]
Бесконечная норма (самостоятельно): 38.000000)
Бесконечная норма (linalg.norm): 38.000000)
Совпадение: True


In [17]:
import numpy as np
from numpy import linalg as LA

#Для вектора, созданного в первом пункте, найти отражение
#Хаусхолдера, которое обнуляет его координаты с 3 по 9.
#Например, вектор (1,2,3,4,5,6,7,8,9) переводит в вектор
#(1,2,0,0,0,0,0,0,0)

vector = np.random.randint(-10, 11, size = (9, 1))
x = vector.flatten()
print(f"\nИсходный вектор x: {x}")

def householder_reflection_correct(x, k):
    n = len(x)
    v_part = x[k:].astype(float).copy()
    if np.allclose(v_part, 0):
        return np.eye(n), x.copy()
    norm_v = np.linalg.norm(v_part)
    sign = np.sign(v_part[0]) if v_part[0] != 0 else 1.0

    u_part = v_part.copy()
    u_part[0] += sign * norm_v

    norm_u = np.linalg.norm(u_part)
    if norm_u > 0:
        u_part = u_part / norm_u

    H = np.eye(n)
    H_sub = np.eye(n - k) - 2.0 * np.outer(u_part, u_part)
    H[k:, k:] = H_sub

    x_new = H @ x

    return H, x_new

H, x_transformed = householder_reflection_correct(x, k=2)

print(f"\nМатрица Хаусхолдера H (размер {H.shape[0]}x{H.shape[1]}):")
np.set_printoptions(precision=4, suppress=True)
print(H)
np.set_printoptions(precision=8, suppress=False)

print(f"\nПреобразованный вектор: {x_transformed}")
print(f"Первые 2 координаты сохранены: {np.allclose(x_transformed[:2], x[:2])}")

print(f"Координаты 4-9 обнулены (индексы 3..8): {np.allclose(x_transformed[3:], 0, atol=1e-10)}")

print(f"\nПроверка ортогональности H:")
print(f"H @ H.T = I: {np.allclose(H @ H.T, np.eye(len(x)))}")
print(f"H.T @ H = I: {np.allclose(H.T @ H, np.eye(len(x)))}")

print(f"\nНорма исходного вектора: {np.linalg.norm(x):.6f}")
print(f"Норма преобразованного вектора: {np.linalg.norm(x_transformed):.6f}")
print(f"Нормы совпадают: {np.isclose(np.linalg.norm(x), np.linalg.norm(x_transformed))}")


Исходный вектор x: [ 4  8  1  9 -8 -6  8 -4 10]

Матрица Хаусхолдера H (размер 9x9):
[[ 1.      0.      0.      0.      0.      0.      0.      0.      0.    ]
 [ 0.      1.      0.      0.      0.      0.      0.      0.      0.    ]
 [ 0.      0.     -0.0526 -0.473   0.4205  0.3154 -0.4205  0.2102 -0.5256]
 [ 0.      0.     -0.473   0.7874  0.189   0.1417 -0.189   0.0945 -0.2362]
 [ 0.      0.      0.4205  0.189   0.832  -0.126   0.168  -0.084   0.21  ]
 [ 0.      0.      0.3154  0.1417 -0.126   0.9055  0.126  -0.063   0.1575]
 [ 0.      0.     -0.4205 -0.189   0.168   0.126   0.832   0.084  -0.21  ]
 [ 0.      0.      0.2102  0.0945 -0.084  -0.063   0.084   0.958   0.105 ]
 [ 0.      0.     -0.5256 -0.2362  0.21    0.1575 -0.21    0.105   0.7376]]

Преобразованный вектор: [ 4.00000000e+00  8.00000000e+00 -1.90262976e+01  3.33066907e-16
  1.11022302e-16 -3.33066907e-16 -1.11022302e-16 -3.88578059e-16
 -8.88178420e-16]
Первые 2 координаты сохранены: True
Координаты 4-9 обнулены (инде

In [20]:
import numpy as np
from numpy import linalg as LA

#Решить систему, используя QR разложение, полученное
#преобразованием Хаусхолдера.
#14.4x_1 - 5.3x_2 + 14.3x_3 - 12.7x_4 = 14.4
#23.4x_1 - 14.2x_2 - 5.4x_3 + 2.1x_4 = 6.6
#6.3x_1 - 13.2x_2 - 6.5x_3 + 14.3x_4 = 9.4
#5.6x_1 + 8.8x_2 - 6.7x_3 - 23.8x_4 = 7.3

m, n = 9, 5
np.random.seed(123)
A = np.random.randint(-10, 11, size = (m,n)).astype(float)
b = np.random.randint(-10, 11, size = m).astype(float)

print(f"\nМатрица A (размер {m}x{n}):\n{A}")
print(f"\nВектор b (размер {m}):\n{b}")

def qr_decomposition_householder(A):
    m,n = A.shape
    R = A.copy()
    Q = np.eye(m)

    for j in range(min(m-1,n)):
        x = R[j:, j]
        norm_x = np.linalg.norm(x)
        if norm_x == 0: continue
        sign = np.sign(x[0] if x[0] != 0 else 1)

        u = x.copy()
        u[0] += sign * norm_x
        u = u / np.linalg.norm(u)

        R[j:, :] = R[j:, :] - 2 * np.outer(u, u @ R[j:, :])
        Q[:, j:] = Q[:, j:] - 2 * np.outer(Q[:, j:] @ u, u)

    return Q, R

Q, R = qr_decomposition_householder(A)
print(f"\nМатрица Q (ортогональная, размер {Q.shape[0]}x{Q.shape[1]}):\n{Q}")
print(f"\nМатрица R (верхнетреугольная, размер {R.shape[0]}x{R.shape[1]}):\n{R}")

print(f"\nПроверка QR разложения:")
print(f"Q @ R = A: {np.allclose(Q @ R, A)}")
print(f"Q ортогональна: {np.allclose(Q.T @ Q, np.eye(Q.shape[0]))}")

QTb = Q.T @ b
print(f"\nQ^T @ b: {QTb}")

R_upper = R[:n, :n]
QTb_reduced = QTb[:n]

print(f"\n R (верхняя {n}x{n} часть): \n{R_upper}")
print(f"Q^T @ b (первые {n} элементов): \n{QTb_reduced}")

def solve_upper_triangular(R,b):
    n = len(b)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - np.dot(R[i, i+1:], x[i+1:])) / R[i, i]
    return x

x_solution = solve_upper_triangular(R_upper,QTb_reduced)
print(f"\nРешение системы x: {x_solution}")

x_check = LA.lstsq(A, b, rcond=None)[0]
print(f"Решение (numpy lstsq): {x_check}")
print(f"Совпадение решений: {np.allclose(x_solution, x_check)}")

residual = np.linalg.norm(A @ x_solution - b)
print(f"\nНевязка ||Ax - b||_2: {residual:.6f}")


Матрица A (размер 9x5):
[[  3.  -8.  -8.  -4.   7.]
 [  9.   0.  -9. -10.   7.]
 [  5.  -1. -10.   4. -10.]
 [  5.   9.   4.  -6. -10.]
 [  6.  -6.   7.  -7.  -8.]
 [ 10.  -3.  -8.  10.   5.]
 [  6.  -3.  -1.  -7.  10.]
 [ -4.  -9.  -8.  -9.   2.]
 [ -2.  -7.   0.  -5. -10.]]

Вектор b (размер 9):
[ 1. -8.  0.  3.  8. -6.  5.  1.  2.]

Матрица Q (ортогональная, размер 9x9):
[[-0.16464639  0.43207124 -0.16730965 -0.06897773  0.15296133 -0.22866695
  -0.54634139 -0.59362527 -0.16398157]
 [-0.49393917 -0.02690067 -0.30466427 -0.50320795  0.15088099 -0.26810881
  -0.11880408  0.41399682  0.35931422]
 [-0.27441065  0.04018495 -0.43132036  0.15995325 -0.61553685 -0.32954932
   0.39220529 -0.11891749 -0.23665787]
 [-0.27441065 -0.51111271  0.10053813 -0.40925675 -0.3532363   0.44900597
  -0.22181403 -0.29371261 -0.1549606 ]
 [-0.32929278  0.31284482  0.71943064 -0.05005163 -0.2413738  -0.19340821
  -0.08164215  0.29085751 -0.2944099 ]
 [-0.5488213   0.13549967 -0.13834151  0.58908561  0.0778